## désactive le swap pr le kubernetes (temporaire)
- name: Disable swap (temp)
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

## la meme chose mais en permanent
- name: Permanently disable swap
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s)'
    replace: '#\1'

## copie le fichier modules.conf 
- name: Load kernel modules
  copy:
    src: modules.conf
    dest: /etc/modules-load.d/k8s.conf

- name: modprobe required modules
  modprobe:
    name: "{{ item }}"
  loop:
    - overlay
    - br_netfilter

- name: Set sysctl params
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply sysctl settings
  command: sysctl --system

