---
- name: Install prerequisites for Docker
  apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes

- name: Create keyrings directory for Docker
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Get system architecture
  command: dpkg --print-architecture
  register: docker_arch
    
- name: Set architecture fact
  set_fact:
    docker_arch: "{{ docker_arch.stdout | trim }}"

- name: Get Ubuntu codename
  command: lsb_release -cs
  register: ubuntu_codename

- name: Add Docker repository
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable
      #      deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ubuntu_codename }} stable


- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name: "{{ docker_packages }}"
    state: present

