---
#- name: Patch containerd config to enable CRI plugin
#  hosts: master
#  become: yes
#  tasks:
#    - name: Replace disabled_plugins by enabled_plugins for cri
#      replace:
#        path: /etc/containerd/config.toml
#        regexp: '^disabled_plugins\s*=.*'
#        replace: 'enabled_plugins = ["cri"]'
#
#    - name: Restart containerd
#      systemd:
#        name: containerd
#        state: restarted
- name: Initialize Kubernetes Master Node
  hosts: master
  become: yes
  tasks:
    - name: Initialize Kubernetes cluster
      command: sudo kubeadm init --pod-network-cidr=192.168.1.0/16
      register: init_output
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Get kubeadm join command
      command: kubeadm token create --print-join-command
      register: join_cmd
      when: init_output is succeeded
      changed_when: false

        
    - name: Save join command to file
      copy:
        content: |
          #!/bin/bash
          sudo {{ join_cmd.stdout }}
        dest: /join.sh
        mode: '0755'
      when: join_cmd is defined

    - name: Share join.sh with Ansible controller
      fetch:
        src: /join.sh
        dest: ./join_command/
        flat: yes
      when: join_cmd is defined

## pr le groupe workers
- name: Join Kubernetes Worker Nodes
  hosts: workers
  become: yes
  tasks:
    - name: Copy join.sh from controller to worker
      copy:
        src: ./join_command/join.sh
        dest: /tmp/join.sh
        mode: '0755'

    - name: Execute join.sh to join cluster
      command: /tmp/join.sh
